// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XFA_API.Models;

#nullable disable

namespace XFA_API.Migrations
{
    [DbContext(typeof(XFAContext))]
    partial class XFAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XFA_API.Models.ActionField", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("DocumentModelid")
                        .HasColumnType("bigint");

                    b.Property<long>("document_id")
                        .HasColumnType("bigint");

                    b.Property<string>("identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("DocumentModelid");

                    b.ToTable("action_field");
                });

            modelBuilder.Entity("XFA_API.Models.DocumentModel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("file_path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("validation_button")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("XFA_API.Models.ExportedFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("exported_file");
                });

            modelBuilder.Entity("XFA_API.Models.InputField", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("DocumentModelid")
                        .HasColumnType("bigint");

                    b.Property<long>("document_id")
                        .HasColumnType("bigint");

                    b.Property<string>("identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("DocumentModelid");

                    b.ToTable("input_fields");
                });

            modelBuilder.Entity("XFA_API.Models.ActionField", b =>
                {
                    b.HasOne("XFA_API.Models.DocumentModel", null)
                        .WithMany("action_fields")
                        .HasForeignKey("DocumentModelid");
                });

            modelBuilder.Entity("XFA_API.Models.InputField", b =>
                {
                    b.HasOne("XFA_API.Models.DocumentModel", null)
                        .WithMany("input_fields")
                        .HasForeignKey("DocumentModelid");
                });

            modelBuilder.Entity("XFA_API.Models.DocumentModel", b =>
                {
                    b.Navigation("action_fields");

                    b.Navigation("input_fields");
                });
#pragma warning restore 612, 618
        }
    }
}
